services:
  flow2api:
    build: .
    container_name: flow2api
    ports:
      - "31800:8000"
    volumes:
      - ./:/app
    environment:
      - HTTP_PROXY=http://192.168.31.1:7890
      - HTTPS_PROXY=http://192.168.31.1:7890
      - PYTHONUNBUFFERED=1
    restart: unless-stopped